FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o api-gateway ./cmd/api-gateway

FROM alpine:3.20

WORKDIR /root/

COPY --from=builder /app/api-gateway .

COPY --from=builder /app/web ./web

EXPOSE 8080

CMD ["./api-gateway"]