%%{init: {'theme': 'base', 'themeVariables': { 'background': '#f5f5f5' }}}%%
sequenceDiagram
    participant C as Cliente
    participant GW as API Gateway
    participant Redis as Redis Pub/Sub
    participant US as User/Group Service
    participant DBL as DB Service (Líder)
    participant DBF as DB Service (Seguidor)

    C->>+GW: 1. Petición HTTP/S
    GW->>Redis: 2. PUBLISH (canal: 'user_events', payload: {...})
    note right of GW: El Gateway espera una respuesta en un canal específico.
    Redis-->>US: 3. Recibe evento (SUBSCRIBE)
    US->>+DBL: 4. Petición HTTP REST a la DB
    DBL->>+DBF: 5. Replicación (AppendEntries RPC)
    DBF-->>-DBL: 6. Ack
    DBL-->>-US: 7. Respuesta de la DB
    US->>Redis: 8. PUBLISH (canal: 'user_events_response', payload: {...})
    Redis-->>GW: 9. Recibe respuesta (SUBSCRIBE)
    GW-->>-C: 10. Respuesta HTTP/S final
