%%{init: {'theme': 'base', 'themeVariables': { 'background': '#f5f5f5' }}}%%
graph TD
    subgraph "Red Externa"
        Client[Cliente]
    end

    subgraph "Infraestructura Distribuida"
        VIP(IP Virtual)

        subgraph "Punto de Entrada (Failover tipo VRRP)"
            GW_A[API Gateway - Activo]
            GW_P[API Gateway - Pasivo]
        end

        subgraph "Capa de Mensajería (Alta Disponibilidad)"
            subgraph "Par Redis"
                Redis_P[Redis - Primario]
                Redis_R[Redis - Réplica]
            end
            subgraph "Supervisión"
                Supervisor[Redis Supervisor]
            end
        end
        
        subgraph "Servicios de Lógica de Negocio (Stateless)"
            direction LR
            US1[User Service R1]
            US2[User Service R2]
            GS1[Group Service R1]
            GS2[Group Service R2]
        end
        
        subgraph "Servicio de Datos (Stateful - Raft)"
            DB_Cluster["Clúster DB Service"]
        end
    end

    Client -- HTTP/S --> VIP
    VIP -- Enrutado a --> GW_A
    GW_P -. Heartbeat .-> GW_A
    
    GW_A -- PUBLISH/SUBSCRIBE --> Redis_P

    Supervisor -- Monitoriza --> Redis_P
    Supervisor -- Monitoriza --> Redis_R
    Supervisor -- Promueve --> Redis_R

    Redis_P -. Replicación .-> Redis_R
    
    US -- Pub/Sub --> Redis_P
    GS -- Pub/Sub --> Redis_P

    US -- HTTP REST --> DB_Cluster
    GS -- HTTP REST --> DB_Cluster

    style GW_A fill:#bbf,stroke:green,stroke-width:4px
    style GW_P fill:#bbf,stroke:#333,stroke-width:2px
    style Redis_P fill:#f88,stroke:green,stroke-width:4px
    style Redis_R fill:#f88,stroke:#333,stroke-width:2px
